[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'chromium', 'chromedriver']

[phases.install]
cmds = ['python3.11 -m pip install --upgrade pip', 'python3.11 -m pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'python3.11 web_app.py'
